

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anita
  
  redis:
    image: redis:7

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  
  celery:
    build: .
    command: celery -A config worker --loglevel=info --pool=solo
    depends_on:
      - db
      - redis
    env_file:
      - .env