# Generated by Django 6.0.5 on 2026-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='has_air_conditioner',
            field=models.BooleanField(default=False),
        ),
    ]
